name: mern-abhi
replicaCount: 2

images:
  - name: abhi-feservice
    repository: public.erc.aws/c3w1m1q2/abhi-feservice
    tag: 5
  - name: abhi-helloservice
    repository: public.erc.aws/c3w1m1q2/abhi-helloservice
    tag: 3
  - name: abhi-profileservice
    repository: public.erc.aws/c3w1m1q2/abhi-profileservice
    tag: 21

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 512Mi
    cpu: "0.2"

services:
  - name: helloservice
    repository: public.erc.aws/c3w1m1q2/abhi-helloservice
    tag: 3
    port: 3001
  - name: profileservice
    repository: public.erc.aws/c3w1m1q2/abhi-profileservice
    tag: 21
    port: 3002
  - name: frontservice
    repository: public.erc.aws/c3w1m1q2/abhi-feservice
    tag: 5
    port: 3000

service:
  name: mern-abhi
  ports:
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
