apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: helloservice
          image: public.ecr.aws/c3w1m1q2/abhi-helloservice:3
          ports:
            - containerPort: 3001
        - name: profileservice
          image: public.ecr.aws/c3w1m1q2/abhi-profileservice:21
          ports:
            - containerPort: 3002
        - name: frontservice
          image: public.ecr.aws/c3w1m1q2/abhi-feservice:5
          ports:
            - containerPort: 3000
        # Add other microservices as needed

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 3000 # Default port for frontservice
    - protocol: TCP
      port: 2001
      targetPort: 3001 # Port for helloservice
    - protocol: TCP
      port: 2002
      targetPort: 3002 # Port for profileservice
  type: LoadBalancer
