apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: helloservice
          image: public.ecr.aws/c3w1m1q2/abhi-helloservice:3
          ports:
            - containerPort: 3001
        - name: profileservice
          image: public.ecr.aws/c3w1m1q2/abhi-profileservice:21
          ports:
            - containerPort: 3002
        - name: frontservice
          image: public.ecr.aws/c3w1m1q2/abhi-feservice:5
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - name: frontservice-port
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: helloservice-port
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: profileservice-port
      protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
